
spring.mail.host=email.gov.in
spring.mail.port=465
spring.mail.username=support.irctc@pcdatravel.gov.in
spring.mail.password=cCGDA321#
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
